name: InfoUI
author: iiFouzi
main: iiFouzi\InfoUI
version: 0.1
description: See information about the server in an UI format!
api: [3.0.0]
commands:
    info:
        default: true
        description: Opens Information Menu!
